name: Build

on: 
  # Trigger the worfklow on pushes to only the 'main' branch
  push:
    branches: [ main ]
  # Trigger the workflow on any PR
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Restore Solution
        run: |
          dotnet restore -v diag -p:RestoreBuildInParallel="false"

      - name: Build Solution
        run: |
          dotnet build
